/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/registration-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["registrationStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logoutAll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["bootstrap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listDecks"];
        put?: never;
        post: operations["createDeck"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decks/{deckId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deckId: components["parameters"]["DeckId"];
            };
            cookie?: never;
        };
        get: operations["deckOverview"];
        put?: never;
        post?: never;
        delete: operations["deleteDeck"];
        options?: never;
        head?: never;
        patch: operations["renameDeck"];
        trace?: never;
    };
    "/decks/{deckId}/reset": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deckId: components["parameters"]["DeckId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resetDeck"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decks/{deckId}/cards": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deckId: components["parameters"]["DeckId"];
            };
            cookie?: never;
        };
        get: operations["listCards"];
        put?: never;
        post: operations["createCard"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decks/{deckId}/cards/parse": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deckId: components["parameters"]["DeckId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["parseCards"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decks/{deckId}/cards/import": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deckId: components["parameters"]["DeckId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["importCards"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cards/{cardId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cardId: components["parameters"]["CardId"];
            };
            cookie?: never;
        };
        get: operations["getCard"];
        put: operations["updateCard"];
        post?: never;
        delete: operations["deleteCard"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cards/{cardId}/reset": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cardId: components["parameters"]["CardId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resetCard"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decks/{deckId}/queue": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deckId: components["parameters"]["DeckId"];
            };
            cookie?: never;
        };
        get: operations["queue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decks/{deckId}/session": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deckId: components["parameters"]["DeckId"];
            };
            cookie?: never;
        };
        get: operations["session"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["answer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/answer/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["answerBatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/statistics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["statistics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSettings"];
        put: operations["updateSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["changePassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            /**
             * @description Stable machine-readable error code.
             * @example validation_error
             * @example queue_refresh
             * @example confirmation_required
             * @example rate_limited
             */
            code: string;
            message: string;
        };
        RegistrationStatus: {
            enabled: boolean;
            inviteRequired: boolean;
        };
        Settings: {
            /** Format: int64 */
            userId: number;
            /** @example 04:00:00 */
            refreshTime: string;
            /** @enum {string} */
            language: "ZH" | "EN";
            /** @enum {string} */
            theme: "SYSTEM" | "LIGHT" | "DARK";
        };
        User: {
            /** Format: int64 */
            id: number;
            /** Format: email */
            email: string;
            settings: components["schemas"]["Settings"];
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            inviteCode: string;
            rememberMe?: boolean;
            /** @enum {string} */
            language?: "ZH" | "EN";
        };
        LoginRequest: {
            email: string;
            password: string;
            rememberMe?: boolean;
        };
        Deck: {
            /** Format: int64 */
            id: number;
            name: string;
            /** Format: int64 */
            newCount: number;
            /** Format: int64 */
            relearnCount: number;
            /** Format: int64 */
            learnRelearnCount: number;
            /** Format: int64 */
            reviewRelearnCount: number;
            /** Format: int64 */
            dueCount: number;
            /** Format: date-time */
            createdAt: string;
        };
        CreateDeckRequest: {
            name: string;
        };
        RenameDeckRequest: {
            name: string;
        };
        Card: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            deckId: number;
            front: string;
            back: string;
            /** Format: int64 */
            position: number;
            /** @enum {string} */
            status: "new" | "review" | "relearn" | "graduated";
            stage: number;
            /** @enum {string} */
            relearnMode: "NONE" | "FORGOT" | "BLURRY";
            relearnCorrectCount: number;
            /** Format: date */
            dueDate?: string | null;
            /** Format: int64 */
            stateVersion: number;
            /** Format: date-time */
            createdAt: string;
        };
        CreateCardRequest: {
            front: string;
            back?: string;
        };
        UpdateCardRequest: {
            front: string;
            back?: string;
        };
        CardList: {
            items: components["schemas"]["Card"][];
            /** Format: int64 */
            total: number;
            page: number;
            pageSize: number;
        };
        DeckOverview: {
            deck: components["schemas"]["Deck"];
            cards: components["schemas"]["CardList"];
        };
        Bootstrap: {
            user: components["schemas"]["User"];
            decks: components["schemas"]["Deck"][];
        };
        Queue: {
            /** Format: int64 */
            deckId: number;
            /** @enum {string} */
            type: "LEARN" | "REVIEW";
            cardIds: number[];
        };
        Session: {
            /** Format: int64 */
            deckId: number;
            /** @enum {string} */
            type: "LEARN" | "REVIEW";
            timezone: string;
            order: number[];
            cards: components["schemas"]["Card"][];
            total: number;
        };
        AnswerRequest: {
            clientAnswerId: string;
            previousClientAnswerId?: string | null;
            /** Format: int64 */
            cardId: number;
            result: components["schemas"]["AnswerResult"];
            /** @enum {string} */
            queueType: "LEARN" | "REVIEW";
            timezone: string;
            /** Format: int64 */
            stateVersion: number;
            graduate?: boolean;
            confirmForget?: boolean;
        };
        /** @enum {string} */
        AnswerResult: "FAMILIAR" | "BLURRY" | "FORGOT";
        AnswerResponse: {
            /** Format: int64 */
            cardId: number;
            clientAnswerId: string;
            accepted: boolean;
            /** Format: int64 */
            nextCardId: number | null;
            completed: boolean;
            requiresConfirmation: boolean;
        };
        AnswerBatchRequest: {
            /** Format: int64 */
            deckId: number;
            /** @enum {string} */
            queueType: "LEARN" | "REVIEW";
            timezone: string;
            items: components["schemas"]["AnswerBatchItemRequest"][];
        };
        AnswerBatchItemRequest: {
            clientAnswerId: string;
            /** Format: int64 */
            cardId: number;
            result: components["schemas"]["AnswerResult"];
            /** Format: int64 */
            stateVersion: number;
            previousClientAnswerId?: string | null;
            graduate?: boolean;
            confirmForget?: boolean;
        };
        AnswerBatchResponse: {
            results: components["schemas"]["AnswerBatchItemResponse"][];
        };
        AnswerBatchItemResponse: {
            /** Format: int64 */
            cardId: number;
            clientAnswerId: string;
            accepted: boolean;
            code: string;
            /** Format: int64 */
            nextCardId: number | null;
            completed: boolean;
            requiresConfirmation: boolean;
        };
        Statistics: {
            /** Format: date */
            learningDay: string;
            /** Format: int64 */
            learnedToday: number;
            /** Format: int64 */
            reviewedToday: number;
            /** Format: int64 */
            tomorrowDue: number;
            /** Format: int64 */
            relearnCount: number;
            stageDistribution: {
                [key: string]: number;
            };
            resultCounts: {
                [key: string]: number;
            };
            retentionRate: number | null;
            hourlyDistribution: {
                [key: string]: number;
            };
            forecast: components["schemas"]["Forecast"];
            deckOptions: components["schemas"]["DeckOption"][];
        };
        Forecast: {
            /** Format: int64 */
            day7: number;
            /** Format: int64 */
            day30: number;
            /** Format: int64 */
            day90: number;
            /** Format: int64 */
            day180: number;
        };
        DeckOption: {
            /** Format: int64 */
            id: number;
            name: string;
            deleted: boolean;
        };
        ParseCardRequest: {
            source: string;
        };
        ImportCardsRequest: {
            rows: components["schemas"]["ImportCardRequest"][];
        };
        ImportCardRequest: {
            front: string;
            back: string;
        };
        ImportPreview: {
            items: components["schemas"]["ImportPreviewItem"][];
            total: number;
            validCount: number;
            duplicateCount: number;
            invalidCount: number;
        };
        ImportPreviewItem: {
            row: number;
            front: string;
            back: string;
            duplicate: boolean;
            errors: string[];
        };
        ImportResult: {
            created: number;
            skippedDuplicates: number;
        };
        UpdateSettingsRequest: {
            /** Format: time */
            refreshTime: string;
            /** @enum {string} */
            language: "ZH" | "EN";
            /** @enum {string} */
            theme: "SYSTEM" | "LIGHT" | "DARK";
        };
        ChangePasswordRequest: {
            currentPassword: string;
            newPassword: string;
        };
    };
    responses: {
        /** @description Error response */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        DeckId: number;
        CardId: number;
        Timezone: string;
        QueueType: "LEARN" | "REVIEW";
        Query: string;
        Status: "new" | "review" | "relearn" | "graduated";
        Page: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    registrationStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registration availability */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistrationStatus"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Registered */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Logged in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Error"];
            429: components["responses"]["Error"];
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logoutAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All sessions logged out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    bootstrap: {
        parameters: {
            query?: {
                timezone?: components["parameters"]["Timezone"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User and deck list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bootstrap"];
                };
            };
        };
    };
    listDecks: {
        parameters: {
            query?: {
                timezone?: components["parameters"]["Timezone"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deck list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deck"][];
                };
            };
        };
    };
    createDeck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDeckRequest"];
            };
        };
        responses: {
            /** @description Created deck */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deck"];
                };
            };
            400: components["responses"]["Error"];
        };
    };
    deckOverview: {
        parameters: {
            query?: {
                timezone?: components["parameters"]["Timezone"];
                q?: components["parameters"]["Query"];
                status?: components["parameters"]["Status"];
                page?: components["parameters"]["Page"];
            };
            header?: never;
            path: {
                deckId: components["parameters"]["DeckId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deck overview */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckOverview"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    deleteDeck: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deckId: components["parameters"]["DeckId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    renameDeck: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deckId: components["parameters"]["DeckId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameDeckRequest"];
            };
        };
        responses: {
            /** @description Renamed deck */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deck"];
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    resetDeck: {
        parameters: {
            query?: {
                timezone?: components["parameters"]["Timezone"];
            };
            header?: never;
            path: {
                deckId: components["parameters"]["DeckId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reset */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listCards: {
        parameters: {
            query?: {
                q?: components["parameters"]["Query"];
                status?: components["parameters"]["Status"];
                page?: components["parameters"]["Page"];
            };
            header?: never;
            path: {
                deckId: components["parameters"]["DeckId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Card list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardList"];
                };
            };
        };
    };
    createCard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deckId: components["parameters"]["DeckId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCardRequest"];
            };
        };
        responses: {
            /** @description Created card */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Card"];
                };
            };
            400: components["responses"]["Error"];
        };
    };
    parseCards: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deckId: components["parameters"]["DeckId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParseCardRequest"];
            };
        };
        responses: {
            /** @description Import preview */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportPreview"];
                };
            };
            400: components["responses"]["Error"];
        };
    };
    importCards: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deckId: components["parameters"]["DeckId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportCardsRequest"];
            };
        };
        responses: {
            /** @description Import result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResult"];
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    getCard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cardId: components["parameters"]["CardId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Card */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Card"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    updateCard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cardId: components["parameters"]["CardId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCardRequest"];
            };
        };
        responses: {
            /** @description Updated card */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Card"];
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    deleteCard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cardId: components["parameters"]["CardId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    resetCard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cardId: components["parameters"]["CardId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reset */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    queue: {
        parameters: {
            query: {
                type: components["parameters"]["QueueType"];
                timezone?: components["parameters"]["Timezone"];
            };
            header?: never;
            path: {
                deckId: components["parameters"]["DeckId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Queue */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Queue"];
                };
            };
            400: components["responses"]["Error"];
        };
    };
    session: {
        parameters: {
            query: {
                type: components["parameters"]["QueueType"];
                timezone?: components["parameters"]["Timezone"];
            };
            header?: never;
            path: {
                deckId: components["parameters"]["DeckId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            400: components["responses"]["Error"];
        };
    };
    answer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerRequest"];
            };
        };
        responses: {
            /** @description Answer result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnswerResponse"];
                };
            };
            409: components["responses"]["Error"];
        };
    };
    answerBatch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerBatchRequest"];
            };
        };
        responses: {
            /** @description Batch answer results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnswerBatchResponse"];
                };
            };
            400: components["responses"]["Error"];
        };
    };
    statistics: {
        parameters: {
            query?: {
                timezone?: components["parameters"]["Timezone"];
                deckId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Statistics"];
                };
            };
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
        };
    };
    updateSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSettingsRequest"];
            };
        };
        responses: {
            /** @description Updated settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            400: components["responses"]["Error"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Password changed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Health */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
